### Creating a dataframe of Start and End timings

https://www.youtube.com/watch?v=DSdQPyLP2O0

In [2]:
import pandas as pd

# Sample DataFrame
data = {
    'Segment No.': list(range(1, 43)),
    'Start Time': ['00:00', '00:26', '00:48', '01:33', '02:13', '02:36', '02:49', '03:10', '03:20', '03:30', '03:48', '05:50', '06:08', '06:27', '07:17', '08:02', '08:19', '08:30', '08:54', '09:07', '09:21', '11:07', '11:54', '12:22', '12:55', '13:42', '14:02', '14:17', '14:57', '15:24', '15:44', '16:20', '17:32', '17:42', '19:21', '20:21', '21:46', '22:38', '23:02', '23:28', '23:42', '24:30'],
    'End Time': ['00:11', '00:37', '00:55', '01:45', '02:32', '02:39', '03:00', '03:18', '03:27', '03:41', '03:53', '06:01', '06:15', '06:30', '07:21', '08:12', '08:25', '08:35', '09:00', '09:16', '09:24', '11:14', '11:59', '12:25', '13:03', '13:52', '14:09', '14:20', '15:12', '15:35', '15:48', '16:27', '17:38', '18:03', '19:36', '20:28', '21:49', '22:59', '23:14', '23:32', '23:54', '24:52']
}

df = pd.DataFrame(data)

In [3]:
df

Segment No. Start Time End Time
0             1      00:00    00:11
1             2      00:26    00:37
2             3      00:48    00:55
3             4      01:33    01:45
4             5      02:13    02:32
5             6      02:36    02:39
6             7      02:49    03:00
7             8      03:10    03:18
8             9      03:20    03:27
9            10      03:30    03:41
10           11      03:48    03:53
11           12      05:50    06:01
12           13      06:08    06:15
13           14      06:27    06:30
14           15      07:17    07:21
15           16      08:02    08:12
16           17      08:19    08:25
17           18      08:30    08:35
18           19      08:54    09:00
19           20      09:07    09:16
20           21      09:21    09:24
21           22      11:07    11:14
22           23      11:54    11:59
23           24      12:22    12:25
24           25      12:55    13:03
25           26      13:42    13:52
26           27      14:02    14:09
27           28      14:17    14:20
28           29      14:57    15:12
29           30      15:24    15:35
30           31      15:44    15:48
31           32      16:20    16:27
32           33      17:32    17:38
33           34      17:42    18:03
34           35      19:21    19:36
35           36      20:21    20:28
36           37      21:46    21:49
37           38      22:38    22:59
38           39      23:02    23:14
39           40      23:28    23:32
40           41      23:42    23:54
41           42      24:30    24:52

In [7]:
lam = lambda x: 'hlt_time_' + str(x)

In [8]:
df['Audio ID'] = df['Segment No.'].apply(lam)

In [9]:
df

Segment No. Start Time End Time     Audio ID
0             1      00:00    00:11   hlt_time_1
1             2      00:26    00:37   hlt_time_2
2             3      00:48    00:55   hlt_time_3
3             4      01:33    01:45   hlt_time_4
4             5      02:13    02:32   hlt_time_5
5             6      02:36    02:39   hlt_time_6
6             7      02:49    03:00   hlt_time_7
7             8      03:10    03:18   hlt_time_8
8             9      03:20    03:27   hlt_time_9
9            10      03:30    03:41  hlt_time_10
10           11      03:48    03:53  hlt_time_11
11           12      05:50    06:01  hlt_time_12
12           13      06:08    06:15  hlt_time_13
13           14      06:27    06:30  hlt_time_14
14           15      07:17    07:21  hlt_time_15
15           16      08:02    08:12  hlt_time_16
16           17      08:19    08:25  hlt_time_17
17           18      08:30    08:35  hlt_time_18
18           19      08:54    09:00  hlt_time_19
19           20      09:07    09:16  hlt_time_20
20           21      09:21    09:24  hlt_time_21
21           22      11:07    11:14  hlt_time_22
22           23      11:54    11:59  hlt_time_23
23           24      12:22    12:25  hlt_time_24
24           25      12:55    13:03  hlt_time_25
25           26      13:42    13:52  hlt_time_26
26           27      14:02    14:09  hlt_time_27
27           28      14:17    14:20  hlt_time_28
28           29      14:57    15:12  hlt_time_29
29           30      15:24    15:35  hlt_time_30
30           31      15:44    15:48  hlt_time_31
31           32      16:20    16:27  hlt_time_32
32           33      17:32    17:38  hlt_time_33
33           34      17:42    18:03  hlt_time_34
34           35      19:21    19:36  hlt_time_35
35           36      20:21    20:28  hlt_time_36
36           37      21:46    21:49  hlt_time_37
37           38      22:38    22:59  hlt_time_38
38           39      23:02    23:14  hlt_time_39
39           40      23:28    23:32  hlt_time_40
40           41      23:42    23:54  hlt_time_41
41           42      24:30    24:52  hlt_time_42

In [4]:
import pandas as pd

# Data
data_2 = {
    'Audio ID': ['Audio_ID_' + str(i) for i in range(152)],
    'Start time': ['00:00', '00:11', '00:21', '00:31', '00:41', '00:51', '01:01', '01:11', '01:21', '01:31',
                   '01:41', '01:51', '02:01', '02:11', '02:21', '02:31', '02:41', '02:51', '03:01', '03:11',
                   '03:21', '03:31', '03:41', '03:51', '04:01', '04:11', '04:21', '04:31', '04:41', '04:51',
                   '05:01', '05:11', '05:21', '05:31', '05:41', '05:51', '06:01', '06:11', '06:21', '06:31',
                   '06:41', '06:51', '07:01', '07:11', '07:21', '07:31', '07:41', '07:51', '08:01', '08:11',
                   '08:21', '08:31', '08:41', '08:51', '09:01', '09:11', '09:21', '09:31', '09:41', '09:51',
                   '10:01', '10:11', '10:21', '10:31', '10:41', '10:51', '11:01', '11:11', '11:21', '11:31',
                   '11:41', '11:51', '12:01', '12:11', '12:21', '12:31', '12:41', '12:51', '13:01', '13:11',
                   '13:21', '13:31', '13:41', '13:51', '14:01', '14:11', '14:21', '14:31', '14:41', '14:51',
                   '15:01', '15:11', '15:21', '15:31', '15:41', '15:51', '16:01', '16:11', '16:21', '16:31',
                   '16:41', '16:51', '17:01', '17:11', '17:21', '17:31', '17:41', '17:51', '18:01', '18:11',
                   '18:21', '18:31', '18:41', '18:51', '19:01', '19:11', '19:21', '19:31', '19:41', '19:51',
                   '20:01', '20:11', '20:21', '20:31', '20:41', '20:51', '21:01', '21:11', '21:21', '21:31',
                   '21:41', '21:51', '22:01', '22:11', '22:21', '22:31', '22:41', '22:51', '23:01', '23:11',
                   '23:21', '23:31', '23:41', '23:51', '24:01', '24:11', '24:21', '24:31', '24:41', '24:51',
                   '25:01', '25:11']
}

# Create DataFrame
df_2 = pd.DataFrame(data_2)


In [5]:
df_2

Audio ID Start time
0      Audio_ID_0      00:00
1      Audio_ID_1      00:11
2      Audio_ID_2      00:21
3      Audio_ID_3      00:31
4      Audio_ID_4      00:41
..            ...        ...
147  Audio_ID_147      24:31
148  Audio_ID_148      24:41
149  Audio_ID_149      24:51
150  Audio_ID_150      25:01
151  Audio_ID_151      25:11

[152 rows x 2 columns]

In [6]:
df.to_csv('Manual_Time.csv', index=False)  # Set index=False to avoid writing row numbers as the first column

In [7]:
df_2.to_csv('Original Segments.csv',index=False)

In [79]:
new_data = pd.read_csv(r"Data/Original Segemnt 3.csv")

In [80]:
new_data

Audio ID Start time Highlight ID  Output Category  Amplitude
0      Audio_ID_0      00:00   hlt_time_1                1   0.045492
1      Audio_ID_1      00:11          NaN                0   0.021193
2      Audio_ID_2      00:21   hlt_time_2                1   0.030566
3      Audio_ID_3      00:31   hlt_time_2                1   0.053649
4      Audio_ID_4      00:41          NaN                0   0.052450
..            ...        ...          ...              ...        ...
146  Audio_ID_146   24:21:00          NaN                0   0.006677
147  Audio_ID_147   24:31:00  hlt_time_42                1   0.026422
148  Audio_ID_148   24:41:00  hlt_time_42                1   0.048371
149  Audio_ID_149   24:51:00  hlt_time_42                1   0.020533
150  Audio_ID_150   25:01:00          NaN                0   0.003294

[151 rows x 5 columns]

import numpy as np
for i in range(len(new_data)):
    if new_data['Highlight ID'][i]== NaN:
        new_data['Output Category'][i]=0
    else:
        new_data['Output Category'][i]=1

In [81]:
import numpy as np

# Fill NaN values in 'Highlight ID' with 0 and then set 'Output Category' accordingly
new_data['Output Category'] = np.where(new_data['Highlight ID'].isnull(), 0, 1)


In [82]:
new_data

Audio ID Start time Highlight ID  Output Category  Amplitude
0      Audio_ID_0      00:00   hlt_time_1                1   0.045492
1      Audio_ID_1      00:11          NaN                0   0.021193
2      Audio_ID_2      00:21   hlt_time_2                1   0.030566
3      Audio_ID_3      00:31   hlt_time_2                1   0.053649
4      Audio_ID_4      00:41          NaN                0   0.052450
..            ...        ...          ...              ...        ...
146  Audio_ID_146   24:21:00          NaN                0   0.006677
147  Audio_ID_147   24:31:00  hlt_time_42                1   0.026422
148  Audio_ID_148   24:41:00  hlt_time_42                1   0.048371
149  Audio_ID_149   24:51:00  hlt_time_42                1   0.020533
150  Audio_ID_150   25:01:00          NaN                0   0.003294

[151 rows x 5 columns]

In [83]:
new_data.to_csv("Data/Original Segemnt 3.csv",index=False)

In [1]:
import pandas as pd

In [8]:
final = pd.read_csv("Data/Original Segemnt 3.csv")

In [9]:
final

Audio ID Start time Highlight ID  Output Category  Amplitude
0      Audio_ID_0      00:00   hlt_time_1                1   0.045492
1      Audio_ID_1      00:11          NaN                0   0.021193
2      Audio_ID_2      00:21   hlt_time_2                1   0.030566
3      Audio_ID_3      00:31   hlt_time_2                1   0.053649
4      Audio_ID_4      00:41          NaN                0   0.052450
..            ...        ...          ...              ...        ...
146  Audio_ID_146   24:21:00          NaN                0   0.006677
147  Audio_ID_147   24:31:00  hlt_time_42                1   0.026422
148  Audio_ID_148   24:41:00  hlt_time_42                1   0.048371
149  Audio_ID_149   24:51:00  hlt_time_42                1   0.020533
150  Audio_ID_150   25:01:00          NaN                0   0.003294

[151 rows x 5 columns]

### Assuming X contains your features and y contains your target variable ('Output Category')

In [18]:
# Assuming your dataframe is named 'data'
X = final['Amplitude']  # Features
y = final['Output Category'] # Target variable

### Training,Testing and Validation Split 

In [19]:
from sklearn.model_selection import train_test_split
X_train_temp, X_temp, y_train_temp, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
test_data = (X_test,y_test)

In [66]:
test_indices = X_test.index

In [67]:
list(test_indices)

[4,
 142,
 111,
 16,
 51,
 42,
 143,
 36,
 55,
 81,
 78,
 124,
 125,
 133,
 146,
 9,
 149,
 137,
 85,
 114,
 27,
 15,
 67]

In [62]:
X_val.index

Index([ 76,  22,  30,  31,  12,  11,  18,  32,  84,  82, 127, 132,  66,  45,
        26,  56,  10,  29,  64, 144,  19,  98, 105],
      dtype='int64')

In [68]:
list(X_train_temp.index)

[109,
 126,
 75,
 113,
 65,
 139,
 108,
 112,
 0,
 60,
 69,
 28,
 40,
 44,
 68,
 134,
 93,
 24,
 25,
 23,
 97,
 39,
 147,
 120,
 47,
 110,
 140,
 73,
 33,
 94,
 104,
 62,
 86,
 95,
 53,
 5,
 96,
 138,
 49,
 35,
 80,
 77,
 34,
 117,
 7,
 43,
 70,
 101,
 123,
 83,
 135,
 136,
 89,
 8,
 13,
 122,
 128,
 3,
 17,
 38,
 72,
 131,
 6,
 115,
 100,
 2,
 63,
 54,
 107,
 50,
 118,
 46,
 119,
 61,
 148,
 79,
 59,
 91,
 41,
 58,
 90,
 48,
 88,
 21,
 57,
 145,
 129,
 37,
 141,
 1,
 52,
 130,
 103,
 99,
 116,
 87,
 74,
 121,
 150,
 20,
 71,
 106,
 14,
 92,
 102]

In [25]:
import numpy as np

# Convert Series to numpy array and reshape
X_train_reshaped = X_train_temp.values.reshape(-1, 1)
X_test_reshaped = X_test.values.reshape(-1, 1)


In [26]:
from sklearn.impute import SimpleImputer

# Initialize SimpleImputer with a strategy (e.g., mean, median, most_frequent)
imputer = SimpleImputer(strategy='mean')

# Fit the imputer on the training data and transform both training and test data
X_train_imputed = imputer.fit_transform(X_train_reshaped)
X_test_imputed = imputer.transform(X_test_reshaped)

# Identify indices where y_train contains NaN values
nan_indices = np.isnan(y_train_temp)

# Remove rows with NaN values from X_train and y_train
X_train_cleaned = X_train_imputed[~nan_indices]
y_train_cleaned = y_train_temp[~nan_indices]

### Logistic Regression 

In [27]:
# Initialize and train the logistic regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_cleaned, y_train_cleaned)

LogisticRegression()

In [28]:
# Initialize and train the logistic regression model
model = LogisticRegression()
model.fit(X_train_cleaned, y_train_temp)

LogisticRegression()

In [29]:
X_test_imputed

array([[0.05245035],
       [0.04100247],
       [0.04106813],
       [0.00579341],
       [0.04629482],
       [0.0316477 ],
       [0.0357003 ],
       [0.02458336],
       [0.02873286],
       [0.03575098],
       [0.03053109],
       [0.00019925],
       [0.0323496 ],
       [0.03266457],
       [0.00667654],
       [0.04639048],
       [0.02053251],
       [0.02128789],
       [0.02553368],
       [0.02351093],
       [0.0349731 ],
       [0.02923476],
       [0.02364453]])

In [30]:
from sklearn.metrics import accuracy_score
# Make predictions on the testing set
y_pred = model.predict(X_test_imputed)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)



Accuracy: 0.4782608695652174


In [31]:
from sklearn.svm import SVC

# Assuming X_train and y_train are your training data and labels
model = SVC(kernel='linear')  # You can choose different kernels like 'rbf' or 'poly'
model.fit(X_train_cleaned, y_train_temp)

SVC(kernel='linear')

In [32]:
# Predicting
predictions = model.predict(X_test_imputed)
# Evaluate the model
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)


Accuracy: 0.4782608695652174


In [33]:
from sklearn.tree import DecisionTreeClassifier

# Assuming X_train and y_train are your training data and labels
model = DecisionTreeClassifier()
model.fit(X_train_cleaned, y_train_temp)

# Predicting
predictions = model.predict(X_test_imputed)
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)


Accuracy: 0.5652173913043478


In [34]:
from sklearn.ensemble import RandomForestClassifier

# Assuming X_train and y_train are your training data and labels
model = RandomForestClassifier()
model.fit(X_train_cleaned, y_train_temp)

# Predicting
predictions = model.predict(X_test_imputed)
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)


Accuracy: 0.5652173913043478


In [35]:
from sklearn.ensemble import GradientBoostingClassifier

# Assuming X_train and y_train are your training data and labels
model = GradientBoostingClassifier()
model.fit(X_train_cleaned, y_train_temp)

# Predicting
predictions = model.predict(X_test_imputed)
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)


Accuracy: 0.5652173913043478


In [36]:
X_test_imputed

array([[0.05245035],
       [0.04100247],
       [0.04106813],
       [0.00579341],
       [0.04629482],
       [0.0316477 ],
       [0.0357003 ],
       [0.02458336],
       [0.02873286],
       [0.03575098],
       [0.03053109],
       [0.00019925],
       [0.0323496 ],
       [0.03266457],
       [0.00667654],
       [0.04639048],
       [0.02053251],
       [0.02128789],
       [0.02553368],
       [0.02351093],
       [0.0349731 ],
       [0.02923476],
       [0.02364453]])

In [37]:
X = X.values.reshape(-1, 1)

In [38]:
model.predict(X)

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0],
      dtype=int64)

In [39]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Assuming X_train and y_train are your training data and labels

# Define the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(1,)),  # Assuming one input feature
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(X_train_cleaned, y_train_temp, epochs=10, batch_size=32)

# Predicting
predictions = model.predict(X_test_imputed)

Epoch 1/10
4/4 [==============================] - 1s 4ms/step - loss: 0.6926 - accuracy: 0.5429
Epoch 2/10
4/4 [==============================] - 0s 2ms/step - loss: 0.6910 - accuracy: 0.6190
Epoch 3/10
4/4 [==============================] - 0s 2ms/step - loss: 0.6891 - accuracy: 0.6190
Epoch 4/10
4/4 [==============================] - 0s 2ms/step - loss: 0.6874 - accuracy: 0.6190
Epoch 5/10
4/4 [==============================] - 0s 2ms/step - loss: 0.6859 - accuracy: 0.6190
Epoch 6/10
4/4 [==============================] - 0s 2ms/step - loss: 0.6843 - accuracy: 0.6190
Epoch 7/10
4/4 [==============================] - 0s 2ms/step - loss: 0.6825 - accuracy: 0.6190
Epoch 8/10
4/4 [==============================] - 0s 2ms/step - loss: 0.6806 - accuracy: 0.6190
Epoch 9/10
4/4 [==============================] - 0s 2ms/step - loss: 0.6791 - accuracy: 0.6190
Epoch 10/10
1/1 [==============================] - 0s 112ms/step


In [40]:
predictions

array([[0.45581478],
       [0.45633858],
       [0.45633468],
       [0.45890483],
       [0.45608076],
       [0.45689842],
       [0.45665586],
       [0.4573247 ],
       [0.45707288],
       [0.45665285],
       [0.45696524],
       [0.459421  ],
       [0.4568564 ],
       [0.45683753],
       [0.45882335],
       [0.4560766 ],
       [0.45760345],
       [0.4575464 ],
       [0.45726576],
       [0.4573922 ],
       [0.4566994 ],
       [0.45704284],
       [0.4573834 ]], dtype=float32)

In [41]:
X

array([[0.04549221],
       [0.02119334],
       [0.03056558],
       [0.05364867],
       [0.05245035],
       [0.04901446],
       [0.02005959],
       [0.00325164],
       [0.00545486],
       [0.04639048],
       [0.04153319],
       [0.00018197],
       [0.00016282],
       [0.04058244],
       [0.05445128],
       [0.02923476],
       [0.00579341],
       [0.02453879],
       [0.00388034],
       [0.0275696 ],
       [0.03672804],
       [0.05519456],
       [0.047046  ],
       [0.03775978],
       [0.02958196],
       [0.05079706],
       [0.03165977],
       [0.0349731 ],
       [0.02714721],
       [0.02959328],
       [0.00021654],
       [0.03013597],
       [0.0361872 ],
       [0.01821566],
       [0.0131348 ],
       [0.01285716],
       [0.02458336],
       [0.02979421],
       [0.02487028],
       [0.0264101 ],
       [0.01071533],
       [0.01975515],
       [0.0316477 ],
       [0.04035711],
       [0.02107544],
       [0.03320917],
       [0.02651404],
       [0.027

In [42]:
model.predict(X)

5/5 [==============================] - 0s 2ms/step


array([[0.45611545],
       [0.45755354],
       [0.45696318],
       [0.45576304],
       [0.45581478],
       [0.45596322],
       [0.45763963],
       [0.45913935],
       [0.45893607],
       [0.4560766 ],
       [0.45631048],
       [0.45942262],
       [0.45942435],
       [0.45636374],
       [0.45572835],
       [0.45704284],
       [0.45890483],
       [0.45732746],
       [0.45908135],
       [0.4571425 ],
       [0.4565944 ],
       [0.45569623],
       [0.4560483 ],
       [0.45653263],
       [0.45702204],
       [0.45588621],
       [0.45689768],
       [0.4566994 ],
       [0.4571678 ],
       [0.45702136],
       [0.4594194 ],
       [0.45698887],
       [0.45662674],
       [0.4577859 ],
       [0.45823252],
       [0.45825765],
       [0.4573247 ],
       [0.45700935],
       [0.4573069 ],
       [0.4572119 ],
       [0.4584515 ],
       [0.45766327],
       [0.45689842],
       [0.4563772 ],
       [0.45756242],
       [0.45680496],
       [0.45720565],
       [0.457

In [43]:
import pandas as pd
final = pd.read_csv("Data/Original Segemnt 3.csv")

In [44]:
new = final.drop(columns=['Audio ID','Start time','Highlight ID'])

In [45]:
X = final['Amplitude']  # Features
y = final['Output Category'] # Target variable

In [46]:
new=new[['Amplitude','Output Category']]

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Define your data here
# Assuming you have your data stored in a variable called 'data'
data = new  # Your data goes here




In [48]:
data[:114]

Amplitude  Output Category
0     0.045492                1
1     0.021193                0
2     0.030566                1
3     0.053649                1
4     0.052450                0
..         ...              ...
109   0.038403                0
110   0.020996                0
111   0.041068                0
112   0.020357                0
113   0.042958                0

[114 rows x 2 columns]

In [49]:
# Split the data into train, test, and validation sets
train_data = data[:114]
test_data = data[114:]
validation_data = train_data[:29]
train_data = train_data[29:]


In [50]:
train_data

Amplitude  Output Category
29    0.029593                0
30    0.000217                0
31    0.030136                0
32    0.036187                0
33    0.018216                0
..         ...              ...
109   0.038403                0
110   0.020996                0
111   0.041068                0
112   0.020357                0
113   0.042958                0

[85 rows x 2 columns]

In [51]:
train_data

Amplitude  Output Category
29    0.029593                0
30    0.000217                0
31    0.030136                0
32    0.036187                0
33    0.018216                0
..         ...              ...
109   0.038403                0
110   0.020996                0
111   0.041068                0
112   0.020357                0
113   0.042958                0

[85 rows x 2 columns]

In [52]:
for i in train_data:
    print(i)

Amplitude
Output Category


In [53]:
# Prepare the features and labels for training
X_train = [row[:-1] for row in train_data[1:]]  # Exclude the first row (column names) and the last column
y_train = [row[-1] for row in train_data[1:]]   # Exclude the first row (column names)


In [54]:
train_data[:-1]

Amplitude  Output Category
29    0.029593                0
30    0.000217                0
31    0.030136                0
32    0.036187                0
33    0.018216                0
..         ...              ...
108   0.029392                1
109   0.038403                0
110   0.020996                0
111   0.041068                0
112   0.020357                0

[84 rows x 2 columns]

In [55]:
l = [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0]

In [56]:
final['Final prediction']=l

In [57]:
final

Audio ID Start time Highlight ID  Output Category  Amplitude  \
0      Audio_ID_0      00:00   hlt_time_1                1   0.045492   
1      Audio_ID_1      00:11          NaN                0   0.021193   
2      Audio_ID_2      00:21   hlt_time_2                1   0.030566   
3      Audio_ID_3      00:31   hlt_time_2                1   0.053649   
4      Audio_ID_4      00:41          NaN                0   0.052450   
..            ...        ...          ...              ...        ...   
146  Audio_ID_146   24:21:00          NaN                0   0.006677   
147  Audio_ID_147   24:31:00  hlt_time_42                1   0.026422   
148  Audio_ID_148   24:41:00  hlt_time_42                1   0.048371   
149  Audio_ID_149   24:51:00  hlt_time_42                1   0.020533   
150  Audio_ID_150   25:01:00          NaN                0   0.003294   

     Final prediction  
0                   1  
1                   0  
2                   1  
3                   1  
4                   1  
..                ...  
146                 0  
147                 1  
148                 1  
149                 0  
150                 0  

[151 rows x 6 columns]

In [58]:
final.to_csv("prediction.csv",index=False)